version: "3.7"
services:

    api:
        container_name: "dupbit-api"
        build: ./api
        env_file:
            - ./.env
        volumes:
            - ./api/src/:/usr/src/app/src/
            - ./api/scripts/:/usr/src/app/scripts/
            - ./.files/:/usr/src/app/.files/
            - ./.certs/:/usr/src/app/.certs/
        restart: always

    # youtube-dl:
    #     build: ./youtube-dl
    #     volumes:
    #       - ./.files/youtube-dl/:/usr/src/app/files/

networks:
    default:
        external:
            name: default-helper
