version: "3.7"
services:
    nginx:
        build: ./nginx
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./.logs/:/etc/logs/
            - ./.certs/:/etc/certs/
            - ./web/dist/:/var/www/dupbit.com/
        restart: always
        ports:
            - "80:80"
            - "443:443"
        networks:
            - dupbit-network
    api:
        build: ./api
        env_file:
            - ./.env
        volumes:
            - ./api/src/:/usr/src/app/src/
            - ./api/scripts/:/usr/src/app/scripts/
            - ./.files/:/usr/src/app/.files/
            - ./.certs/:/usr/src/app/.certs/
        restart: always
        depends_on:
            - database
        networks:
            - dupbit-network
    youtube-dl:
        build: ./youtube-dl
        volumes:
          - ./.files/youtube-dl/:/usr/src/app/files/
        networks:
          - dupbit-network
    database:
        image: mariadb:latest
        env_file:
            - ./.env
        ports:
            - "3306:3306"
        volumes:
            - ./.database/:/var/lib/mysql
        restart: always
        networks:
            - dupbit-network
networks:
    dupbit-network:
        name: dupbit-network
        driver: bridge
