version: "3"
services:
    nginx:
        build: ./nginx
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./.logs/:/etc/logs/
            - ./secrets/:/etc/secrets/
        depends_on:
            - web
        restart: always
        ports:
            - "80:80"
            - "443:443"
        networks:
            - prime
    web:
        build: ./node
        volumes:
            - ./node/config.json:/usr/src/app/config.json
            - ./node/pages/:/usr/src/app/pages/
            - ./node/api/:/usr/src/app/api/
            - ./node/src/:/usr/src/app/src/
            - ./files/youtube-dl/:/usr/src/app/data/music/
            - ./node/data/secrets/:/usr/src/app/data/secrets/
        depends_on:
            - database
        restart: always
        networks:
            - prime
    youtube-dl:
        build: ./youtube-dl
        volumes:
          - ./files/youtube-dl/:/usr/src/app/files/
        networks:
          - prime
    database:
        image: mariadb:10.3.5
        environment:
            - MYSQL_RANDOM_ROOT_PASSWORD=1
        ports:
            - "3306:3306"
        volumes:
            - ./.database/:/var/lib/mysql
        restart: always
        networks:
            - prime
networks:
    prime:
        driver: bridge
