version: "3"
services:
  web:
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config.json:/usr/src/app/config.json
      - ./data/secrets/:/usr/src/app/data/secrets/
      - ./pages/:/usr/src/app/pages/
      - ./src/:/usr/src/app/src/
      - ./data/music/:/usr/src/app/data/music/
    depends_on:
      - mariadbdupbit
    links:
      - "mariadbdupbit:database"
    restart: always
  mariadbdupbit:
    image: mariadb:10.3.5
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    ports:
      - "3306:3306"
    volumes:
      - .db/:/var/lib/mysql
    restart: always
